extends SceneTree
## Renders a side view of every tree model into one atlas (assets/impostors/trees.png, 4 x 4 cells
## of 256 px) and writes scripts/impostor_data.gd with each tree's cell and size. Distant tree
## chunks draw these as camera-facing cards (one draw call per chunk). Needs a window:
##   godot --path . --script res://tools/render_impostors.gd

const CELL := 256
const COLS := 4
const MODELS := ["mk:tree", "mk:tree_2", "mk:tree_3", "mk:tree_4", "mk:tree_5", "mk:twisted_tree_4",
	"mk:pine", "mk:pine_2", "mk:pine_3", "mk:pine_4", "mk:pine_5",
	"mk:dead_tree", "mk:dead_tree_2", "mk:dead_tree_3", "tree_palmTall", "tree_palm"]
var vp: SubViewport
var cam: Camera3D
var holder: Node3D

func _init() -> void:
	_run.call_deferred()

func _path(model: String) -> String:
	if model.begins_with("mk:"):
		return "res://assets/megakit/" + model.substr(3) + ".scn"
	return "res://assets/nature/" + model + ".glb"

func _setup() -> void:
	vp = SubViewport.new()
	vp.size = Vector2i(CELL, CELL)
	vp.transparent_bg = true
	vp.own_world_3d = true
	vp.render_target_update_mode = SubViewport.UPDATE_ALWAYS
	root.add_child(vp)
	var env := WorldEnvironment.new()
	var e := Environment.new()
	e.background_mode = Environment.BG_CLEAR_COLOR
	e.ambient_light_source = Environment.AMBIENT_SOURCE_COLOR
	e.ambient_light_color = Color(0.8, 0.85, 0.9)
	e.ambient_light_energy = 0.75
	e.tonemap_mode = Environment.TONE_MAPPER_LINEAR
	env.environment = e
	vp.add_child(env)
	var sun := DirectionalLight3D.new()
	sun.rotation_degrees = Vector3(-50, -30, 0)
	sun.light_energy = 1.0
	vp.add_child(sun)
	cam = Camera3D.new()
	cam.projection = Camera3D.PROJECTION_ORTHOGONAL
	vp.add_child(cam)
	holder = Node3D.new()
	vp.add_child(holder)

func _bounds(n: Node3D) -> AABB:
	var box := AABB()
	var first := true
	for m: MeshInstance3D in n.find_children("*", "MeshInstance3D", true, false):
		var b := m.global_transform * m.get_aabb()
		box = b if first else box.merge(b)
		first = false
	return box

func _run() -> void:
	_setup()
	var atlas := Image.create(CELL * COLS, CELL * COLS, false, Image.FORMAT_RGBA8)
	var lines := PackedStringArray()
	for i in MODELS.size():
		for c in holder.get_children(): c.free()
		var inst: Node3D = (load(_path(MODELS[i])) as PackedScene).instantiate()
		holder.add_child(inst)
		await process_frame
		var box := _bounds(inst)
		# Square cell: model centred left-right, its lowest point on the cell's bottom edge
		var side := maxf(box.size.y, maxf(box.size.x, box.size.z)) * 1.02
		var center := box.get_center()
		cam.size = side
		cam.position = Vector3(center.x, box.position.y + side * 0.5, center.z + 50.0)
		cam.rotation = Vector3.ZERO
		for k in 4: await process_frame
		await RenderingServer.frame_post_draw
		var img := vp.get_texture().get_image()
		img.convert(Image.FORMAT_RGBA8)
		atlas.blit_rect(img, Rect2i(0, 0, CELL, CELL), Vector2i((i % COLS) * CELL, (i / COLS) * CELL))
		# side and lowest point in model units (offset from the model origin)
		lines.append('\t"%s": [%d, %.4f, %.4f, %.4f],' % [MODELS[i], i, side, box.position.y, center.x])
		print("IMPOSTOR ", MODELS[i], " side=", side)
	# Bleed colour into transparent pixels so mipmaps don't darken the edges
	atlas.fix_alpha_edges()
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path("res://assets/impostors"))
	atlas.save_png(ProjectSettings.globalize_path("res://assets/impostors/trees.png"))
	var f := FileAccess.open("res://scripts/impostor_data.gd", FileAccess.WRITE)
	f.store_string("class_name RoyaleImpostors\n## Generated by tools/render_impostors.gd: model -> [atlas cell, cell side, lowest y, centre x]\n## (model units; multiply by the instance scale).\nconst COLS := %d\nconst TREES := {\n%s\n}\n" % [COLS, "\n".join(lines)])
	f.close()
	print("IMPOSTORS_DONE")
	quit()
