-- CLASS APP feature schema update
-- Run this in the Supabase SQL editor for the project used by script.js.

create or replace function public.class_app_username()
returns text
language plpgsql
stable
as $$
declare
  headers jsonb := '{}'::jsonb;
begin
  begin
    headers := coalesce(current_setting('request.headers', true), '{}')::jsonb;
  exception when others then
    headers := '{}'::jsonb;
  end;
  return nullif(headers->>'x-class-username', '');
end;
$$;

create or replace function public.class_app_is_admin()
returns boolean
language sql
stable
as $$
  select public.class_app_username() = 'Marquillero';
$$;

alter table public.profiles
  add column if not exists username_last_changed_at timestamptz;

alter table public.folders
  add column if not exists permissions jsonb not null default '{"viewers":[],"editors":[],"everyone":"edit"}'::jsonb,
  add column if not exists folder_type text;

alter table public.folders
  alter column permissions set default '{"viewers":[],"editors":[],"everyone":"edit"}'::jsonb;

update public.folders
set permissions = coalesce(permissions, '{}'::jsonb) || '{"everyone":"edit"}'::jsonb
where not coalesce(permissions, '{}'::jsonb) ? 'everyone';

alter table public.files
  add column if not exists moved_at timestamptz,
  add column if not exists is_original_upload boolean not null default true,
  add column if not exists source_file_id text;

create table if not exists public.shared_ai_outputs (
  id bigint generated by default as identity primary key,
  sharer text not null,
  provider text,
  prompt text,
  output text,
  created_at timestamptz not null default now()
);

create table if not exists public.shared_announcements (
  id bigint generated by default as identity primary key,
  sharer text not null,
  title text not null,
  body text not null,
  date_key text,
  date_label text,
  schedule text,
  source_type text,
  created_at timestamptz not null default now()
);

create table if not exists public.app_updates (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  active boolean not null default true,
  created_by text,
  created_at timestamptz not null default now(),
  expires_at timestamptz
);

create table if not exists public.code_lab_completions (
  id bigint generated by default as identity primary key,
  username text not null,
  challenge_id text not null,
  challenge_date date not null,
  points integer not null default 1,
  created_at timestamptz not null default now(),
  unique (username, challenge_id, challenge_date)
);

create or replace function public.class_app_contribution_tally()
returns table(username text, total bigint)
language sql
stable
security definer
set search_path = public
as $$
  select files.uploader::text as username, count(*)::bigint as total
  from public.files
  where coalesce(files.is_original_upload, true) = true
    and nullif(files.uploader, '') is not null
  group by files.uploader
  order by total desc, username asc;
$$;

grant execute on function public.class_app_contribution_tally() to anon, authenticated;

create or replace function public.class_app_can_view_folder(folder_row public.folders)
returns boolean
language sql
stable
as $$
  select
    not (
      coalesce(folder_row.folder_type, '') = 'profile'
      or coalesce(folder_row.parent, '') like 'profile:%'
    )
    or folder_row.owner = public.class_app_username()
    or public.class_app_is_admin()
    or coalesce(folder_row.permissions->>'everyone', 'edit') in ('view', 'edit')
    or coalesce(folder_row.permissions->'viewers', '[]'::jsonb) ? public.class_app_username()
    or coalesce(folder_row.permissions->'editors', '[]'::jsonb) ? public.class_app_username();
$$;

create or replace function public.class_app_can_edit_folder(folder_row public.folders)
returns boolean
language sql
stable
as $$
  select
    public.class_app_is_admin()
    or folder_row.owner = public.class_app_username()
    or (
      not (
        coalesce(folder_row.folder_type, '') = 'profile'
        or coalesce(folder_row.parent, '') like 'profile:%'
      )
      and public.class_app_username() is not null
    )
    or coalesce(folder_row.permissions->>'everyone', 'edit') = 'edit'
    or coalesce(folder_row.permissions->'editors', '[]'::jsonb) ? public.class_app_username();
$$;

create or replace function public.class_app_can_place_folder(folder_parent text, folder_owner text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.class_app_is_admin()
    or (
      folder_owner = public.class_app_username()
      and (
        folder_parent is null
        or folder_parent = ''
        or folder_parent = 'profile:' || public.class_app_username()
        or (
          folder_parent not like 'profile:%'
          and not exists (
            select 1 from public.folders parent_folder
            where parent_folder.id::text = folder_parent
          )
        )
        or exists (
          select 1 from public.folders parent_folder
          where parent_folder.id::text = folder_parent
            and public.class_app_can_edit_folder(parent_folder)
        )
      )
    );
$$;

alter table public.folders enable row level security;
alter table public.files enable row level security;
alter table public.shared_ai_outputs enable row level security;
alter table public.shared_announcements enable row level security;
alter table public.app_updates enable row level security;
alter table public.code_lab_completions enable row level security;

drop policy if exists "class folders select" on public.folders;
create policy "class folders select" on public.folders
for select using (public.class_app_can_view_folder(folders));

drop policy if exists "class folders insert" on public.folders;
create policy "class folders insert" on public.folders
for insert with check (public.class_app_can_place_folder(parent, owner));

drop policy if exists "class folders update" on public.folders;
create policy "class folders update" on public.folders
for update using (
  public.class_app_is_admin()
  or owner = public.class_app_username()
) with check (public.class_app_can_place_folder(parent, owner));

drop policy if exists "class folders delete" on public.folders;
create policy "class folders delete" on public.folders
for delete using (
  public.class_app_is_admin()
  or owner = public.class_app_username()
);

drop policy if exists "class files select" on public.files;
create policy "class files select" on public.files
for select using (
  exists (
    select 1 from public.folders f
    where f.id::text = files.folder_id::text
      and public.class_app_can_view_folder(f)
  )
);

drop policy if exists "class files insert" on public.files;
create policy "class files insert" on public.files
for insert with check (
  exists (
    select 1 from public.folders f
    where f.id::text = files.folder_id::text
      and public.class_app_can_edit_folder(f)
  )
);

drop policy if exists "class files update" on public.files;
create policy "class files update" on public.files
for update using (
  exists (
    select 1 from public.folders f
    where f.id::text = files.folder_id::text
      and public.class_app_can_edit_folder(f)
  )
) with check (
  exists (
    select 1 from public.folders f
    where f.id::text = files.folder_id::text
      and public.class_app_can_edit_folder(f)
  )
);

drop policy if exists "class files delete" on public.files;
create policy "class files delete" on public.files
for delete using (
  exists (
    select 1 from public.folders f
    where f.id::text = files.folder_id::text
      and public.class_app_can_edit_folder(f)
  )
);

drop policy if exists "shared ai read" on public.shared_ai_outputs;
create policy "shared ai read" on public.shared_ai_outputs for select using (true);

drop policy if exists "shared ai insert" on public.shared_ai_outputs;
create policy "shared ai insert" on public.shared_ai_outputs
for insert with check (sharer = public.class_app_username());

drop policy if exists "shared ai delete owner" on public.shared_ai_outputs;
create policy "shared ai delete owner" on public.shared_ai_outputs
for delete using (
  sharer = public.class_app_username()
  or public.class_app_is_admin()
);

drop policy if exists "shared announcements read" on public.shared_announcements;
create policy "shared announcements read" on public.shared_announcements for select using (true);

drop policy if exists "shared announcements insert" on public.shared_announcements;
create policy "shared announcements insert" on public.shared_announcements
for insert with check (sharer = public.class_app_username());

drop policy if exists "app updates read" on public.app_updates;
create policy "app updates read" on public.app_updates for select using (active = true);

drop policy if exists "app updates admin insert" on public.app_updates;
create policy "app updates admin insert" on public.app_updates
for insert with check (public.class_app_is_admin());

drop policy if exists "code lab completions read" on public.code_lab_completions;
create policy "code lab completions read" on public.code_lab_completions
for select using (true);

drop policy if exists "code lab completions insert self" on public.code_lab_completions;
create policy "code lab completions insert self" on public.code_lab_completions
for insert with check (
  username = public.class_app_username()
  and points = 1
);

create or replace function public.class_app_claim_code_lab_point(
  p_challenge_id text,
  p_challenge_date date
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  actor text := public.class_app_username();
begin
  if actor is null then
    raise exception 'Login required';
  end if;

  insert into public.code_lab_completions (username, challenge_id, challenge_date, points)
  values (actor, p_challenge_id, p_challenge_date, 1)
  on conflict (username, challenge_id, challenge_date) do nothing;

  if found then
    return 'claimed';
  end if;
  return 'already_claimed';
end;
$$;

create or replace function public.class_app_code_lab_leaderboard()
returns table(username text, total_points bigint)
language sql
stable
security definer
set search_path = public
as $$
  select c.username, sum(c.points)::bigint as total_points
  from public.code_lab_completions c
  group by c.username
  order by total_points desc, c.username asc;
$$;

grant execute on function public.class_app_claim_code_lab_point(text, date) to anon, authenticated;
grant execute on function public.class_app_code_lab_leaderboard() to anon, authenticated;

do $$
begin
  alter publication supabase_realtime add table public.shared_ai_outputs;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.shared_announcements;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.app_updates;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.code_lab_completions;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.files;
exception when duplicate_object then null;
end $$;
