class_name RoyaleImpostors
## Generated by tools/render_impostors.gd: model -> [atlas cell, cell side, lowest y, centre x]
## (model units; multiply by the instance scale).
const COLS := 4
const TREES := {
	"mk:tree": [0, 9.6137, -0.2428, 0.0450],
	"mk:tree_2": [1, 9.6271, -0.2428, 0.1157],
	"mk:tree_3": [2, 7.7959, -0.2428, 0.0091],
	"mk:tree_4": [3, 7.4101, -0.2428, -0.0387],
	"mk:tree_5": [4, 7.1464, -0.2428, -0.0768],
	"mk:twisted_tree_4": [5, 15.9754, -0.2015, 1.0009],
	"mk:pine": [6, 7.4633, -0.2351, 0.0235],
	"mk:pine_2": [7, 8.8983, -0.2351, 0.2224],
	"mk:pine_3": [8, 10.4412, -0.2351, 0.0292],
	"mk:pine_4": [9, 7.5400, -0.2351, -0.3080],
	"mk:pine_5": [10, 7.5238, -0.2351, -0.0279],
	"mk:dead_tree": [11, 13.0264, -0.3356, 0.6177],
	"mk:dead_tree_2": [12, 13.5460, -0.3356, -0.6538],
	"mk:dead_tree_3": [13, 9.6854, -0.3356, 0.4821],
	"tree_palmTall": [14, 1.3828, -0.0500, 0.0000],
	"tree_palm": [15, 1.5449, -0.0500, 0.0000],
}
