-- Migration 002: Create application tables

create table if not exists public.shared_ai_outputs (
  id bigint generated by default as identity primary key,
  sharer text not null, provider text, prompt text, output text,
  created_at timestamptz not null default now()
);

create table if not exists public.shared_announcements (
  id bigint generated by default as identity primary key,
  sharer text not null, title text not null, body text not null,
  date_key text, date_label text, schedule text, source_type text,
  created_at timestamptz not null default now()
);

create table if not exists public.app_updates (
  id bigint generated by default as identity primary key,
  title text not null, message text not null,
  active boolean not null default true,
  created_by text, created_at timestamptz not null default now(),
  expires_at timestamptz
);

create table if not exists public.code_lab_completions (
  id bigint generated by default as identity primary key,
  username text not null, challenge_id text not null,
  challenge_date date not null, points integer not null default 1,
  created_at timestamptz not null default now(),
  unique (username, challenge_id, challenge_date)
);

create table if not exists public.app_open_counts (
  username text primary key,
  count integer not null default 0,
  last_opened_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.class_app_record_app_open(p_local_count integer default 1)
returns table(username text, count integer, total bigint)
language plpgsql security definer set search_path = public as $$
declare
  actor text := public.class_app_username();
  local_count integer := greatest(1, coalesce(p_local_count, 1));
begin
  if actor is null then raise exception 'Missing CLASS APP username'; end if;
  insert into public.app_open_counts as a (username, count, last_opened_at, updated_at)
  values (actor, local_count, now(), now())
  on conflict (username) do update
    set count = greatest(a.count + 1, excluded.count),
        last_opened_at = now(), updated_at = now();
  return query select c.username, c.count,
    (select coalesce(sum(all_counts.count),0)::bigint from public.app_open_counts all_counts) as total
    from public.app_open_counts c where c.username = actor;
end; $$;

create or replace function public.class_app_app_open_tally()
returns table(username text, count integer, last_opened_at timestamptz)
language sql stable security definer set search_path = public as $$
  select a.username, a.count, a.last_opened_at from public.app_open_counts a
  order by a.count desc, a.username asc; $$;

grant execute on function public.class_app_record_app_open(integer) to anon, authenticated;
grant execute on function public.class_app_app_open_tally() to anon, authenticated;

create or replace function public.class_app_contribution_tally()
returns table(username text, total bigint)
language sql stable security definer set search_path = public as $$
  select files.uploader::text as username, count(*)::bigint as total
  from public.files
  where coalesce(files.is_original_upload, true) = true
    and nullif(files.uploader, '') is not null
  group by files.uploader order by total desc, username asc; $$;

grant execute on function public.class_app_contribution_tally() to anon, authenticated;

create or replace function public.class_app_claim_code_lab_point(p_challenge_id text, p_challenge_date date)
returns text language plpgsql security definer set search_path = public as $$
declare actor text := public.class_app_username();
begin
  if actor is null then raise exception 'Login required'; end if;
  insert into public.code_lab_completions (username, challenge_id, challenge_date, points)
  values (actor, p_challenge_id, p_challenge_date, 1)
  on conflict (username, challenge_id, challenge_date) do nothing;
  if found then return 'claimed'; end if;
  return 'already_claimed';
end; $$;

create or replace function public.class_app_code_lab_leaderboard()
returns table(username text, total_points bigint)
language sql stable security definer set search_path = public as $$
  select c.username, sum(c.points)::bigint as total_points
  from public.code_lab_completions c
  group by c.username order by total_points desc, c.username asc; $$;

grant execute on function public.class_app_claim_code_lab_point(text, date) to anon, authenticated;
grant execute on function public.class_app_code_lab_leaderboard() to anon, authenticated;
