-- Migration 005: Emoji reactions table + admin helper functions

-- Emoji reactions (Phase 6 #28)
create table if not exists public.message_reactions (
  id       bigint generated by default as identity primary key,
  message_id text not null,
  username   text not null,
  emoji      text not null,
  created_at timestamptz not null default now(),
  unique (message_id, username, emoji)
);

alter table public.message_reactions enable row level security;

drop policy if exists "reactions read"        on public.message_reactions;
drop policy if exists "reactions insert self"  on public.message_reactions;
drop policy if exists "reactions delete self"  on public.message_reactions;

create policy "reactions read"       on public.message_reactions for select using (true);
create policy "reactions insert self" on public.message_reactions
  for insert with check (username = public.class_app_username());
create policy "reactions delete self" on public.message_reactions
  for delete using (username = public.class_app_username() or public.class_app_is_admin());

-- Admin: delete any user (Phase 6 #29)
create or replace function public.class_app_admin_delete_user(p_username text)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.class_app_is_admin() then raise exception 'Admin only'; end if;
  delete from public.profiles where username = p_username;
end; $$;

grant execute on function public.class_app_admin_delete_user(text) to anon, authenticated;

-- Admin: overall stats snapshot (Phase 6 #29)
create or replace function public.class_app_admin_stats()
returns json language sql stable security definer set search_path = public as $$
  select json_build_object(
    'total_users',   (select count(*) from public.profiles),
    'online_users',  (select count(*) from public.profiles where online = true),
    'total_messages',(select count(*) from public.messages),
    'total_files',   (select count(*) from public.files),
    'total_opens',   (select coalesce(sum(count),0) from public.app_open_counts)
  ); $$;

grant execute on function public.class_app_admin_stats() to anon, authenticated;
