-- Migration 006: Activity log + subject-scoped announcements

-- #30: Activity log
create table if not exists public.activity_log (
  id         bigint generated by default as identity primary key,
  username   text not null,
  action     text not null,
  details    text not null default '',
  created_at timestamptz not null default now()
);

alter table public.activity_log enable row level security;

drop policy if exists "log read admin"   on public.activity_log;
drop policy if exists "log insert self"  on public.activity_log;

create policy "log read admin"  on public.activity_log
  for select using (public.class_app_is_admin());
create policy "log insert self" on public.activity_log
  for insert with check (username = public.class_app_username());

-- Admin helper: read recent activity
create or replace function public.class_app_admin_activity_log(p_limit int default 100)
returns table (id bigint, username text, action text, details text, created_at timestamptz)
language sql stable security definer set search_path = public as $$
  select id, username, action, details, created_at
  from public.activity_log
  order by created_at desc
  limit p_limit;
$$;

grant execute on function public.class_app_admin_activity_log(int) to anon, authenticated;

-- #31: Subject-scoped announcements
create table if not exists public.subject_announcements (
  id           bigint generated by default as identity primary key,
  subject_code text not null,
  posted_by    text not null,
  title        text not null,
  body         text not null default '',
  created_at   timestamptz not null default now()
);

alter table public.subject_announcements enable row level security;

drop policy if exists "subj ann read"         on public.subject_announcements;
drop policy if exists "subj ann insert admin"  on public.subject_announcements;
drop policy if exists "subj ann delete admin"  on public.subject_announcements;

create policy "subj ann read"        on public.subject_announcements for select using (true);
create policy "subj ann insert admin" on public.subject_announcements
  for insert with check (public.class_app_is_admin());
create policy "subj ann delete admin" on public.subject_announcements
  for delete using (public.class_app_is_admin());
