-- Migration 009: Alarm Clock with Web Push support

-- User alarms table
create table if not exists public.user_alarms (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  alarm_time text not null, -- HH:MM format
  label text not null,
  sound_id text not null default 'beep',
  enabled boolean not null default true,
  triggered boolean not null default false,
  repeat_days text, -- JSON array of 0-6 (Sun-Sat) or null for one-time
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, alarm_time, label)
);

-- Push notification subscriptions for alarms
create table if not exists public.alarm_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null,
  auth text not null, -- base64 auth secret
  p256dh text not null, -- base64 ECDH public key
  created_at timestamptz not null default now(),
  unique(user_id, endpoint)
);

-- Function to mark alarm as triggered and reset if it repeats
create or replace function public.alarm_mark_triggered(p_alarm_id bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.user_alarms
  set triggered = true, updated_at = now()
  where id = p_alarm_id;
end; $$;

grant execute on function public.alarm_mark_triggered(bigint) to authenticated;

-- Function to get current alarms that should fire
create or replace function public.get_alarms_to_fire()
returns table(
  id bigint,
  user_id uuid,
  alarm_time text,
  label text,
  sound_id text
) language sql security definer set search_path = public as $$
  select a.id, a.user_id, a.alarm_time, a.label, a.sound_id
  from public.user_alarms a
  where a.enabled = true
    and a.triggered = false
    and a.alarm_time <= to_char(now() at time zone 'UTC', 'HH24:MI')
  order by a.created_at;
$$ stable;

grant execute on function public.get_alarms_to_fire() to authenticated, service_role;

-- Function to get subscriptions for a user
create or replace function public.get_user_alarm_subscriptions(p_user_id uuid)
returns table(
  id bigint,
  endpoint text,
  auth text,
  p256dh text
) language sql security definer set search_path = public as $$
  select s.id, s.endpoint, s.auth, s.p256dh
  from public.alarm_push_subscriptions s
  where s.user_id = p_user_id;
$$ stable;

grant execute on function public.get_user_alarm_subscriptions(uuid) to authenticated, service_role;

-- Function to delete invalid subscription
create or replace function public.delete_alarm_subscription(p_subscription_id bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  delete from public.alarm_push_subscriptions where id = p_subscription_id;
end; $$;

grant execute on function public.delete_alarm_subscription(bigint) to service_role;

-- RLS for user_alarms
alter table public.user_alarms enable row level security;
create policy "Users can view their own alarms"
  on public.user_alarms for select
  using (auth.uid() = user_id);
create policy "Users can insert their own alarms"
  on public.user_alarms for insert
  with check (auth.uid() = user_id);
create policy "Users can update their own alarms"
  on public.user_alarms for update
  using (auth.uid() = user_id);
create policy "Users can delete their own alarms"
  on public.user_alarms for delete
  using (auth.uid() = user_id);

-- RLS for alarm_push_subscriptions
alter table public.alarm_push_subscriptions enable row level security;
create policy "Users can view their own subscriptions"
  on public.alarm_push_subscriptions for select
  using (auth.uid() = user_id);
create policy "Users can insert their own subscriptions"
  on public.alarm_push_subscriptions for insert
  with check (auth.uid() = user_id);
create policy "Users can delete their own subscriptions"
  on public.alarm_push_subscriptions for delete
  using (auth.uid() = user_id);
