-- Migration 010: Create reviewers table for shared study notes
-- Run in Supabase SQL editor

create table if not exists public.reviewers (
  id          bigint generated by default as identity primary key,
  user_id     text not null,
  contributor_name text not null,
  title       text not null,
  summary_content text not null,
  original_file_name text,
  summary_type text not null default 'shared-note',
  is_shared   boolean not null default true,
  created_at  timestamptz not null default now(),
  shared_at   timestamptz not null default now()
);

alter table public.reviewers enable row level security;

-- Everyone (including anonymous) can read shared reviewers
drop policy if exists "reviewers select shared" on public.reviewers;
create policy "reviewers select shared" on public.reviewers
  for select using (is_shared = true);

-- Any logged-in user can insert, but user_id must match their username
drop policy if exists "reviewers insert own" on public.reviewers;
create policy "reviewers insert own" on public.reviewers
  for insert with check (user_id = public.class_app_username());

-- Only the owner or admin can delete
drop policy if exists "reviewers delete own or admin" on public.reviewers;
create policy "reviewers delete own or admin" on public.reviewers
  for delete using (
    user_id = public.class_app_username()
    or public.class_app_is_admin()
  );
