-- Migration 019: Add operation audit log for sensitive actions
-- Helps detect and investigate unauthorized operations on sensitive data
-- This is a defensive logging layer while awaiting Phase 3's JWT migration

create table if not exists public.operation_audit_log (
  id                bigint generated by default as identity primary key,
  operation_type    text not null,  -- 'delete', 'update', 'insert', 'admin-call', etc.
  table_name        text not null,
  record_id         text,
  actor_username    text,           -- from x-class-username header
  details           jsonb,          -- additional context
  created_at        timestamptz not null default now()
);

-- Create index for performance
create index if not exists idx_audit_log_created_at on public.operation_audit_log(created_at desc);
create index if not exists idx_audit_log_actor on public.operation_audit_log(actor_username);
create index if not exists idx_audit_log_operation on public.operation_audit_log(operation_type);

-- Enable RLS on audit log
alter table public.operation_audit_log enable row level security;

-- Audit logs are write-only for authenticated users, read-only for admins
drop policy if exists "audit read admin" on public.operation_audit_log;
create policy "audit read admin" on public.operation_audit_log
  for select using (public.class_app_is_admin());

drop policy if exists "audit write any" on public.operation_audit_log;
create policy "audit write any" on public.operation_audit_log
  for insert with check (true);

-- Helper function to log operations (called from triggers or explicitly)
create or replace function public.class_app_log_operation(
  p_operation_type text,
  p_table_name text,
  p_record_id text default null,
  p_details jsonb default null
)
returns void language plpgsql security definer set search_path = public as $$
begin
  insert into public.operation_audit_log (operation_type, table_name, record_id, actor_username, details)
  values (p_operation_type, p_table_name, p_record_id, public.class_app_username(), p_details);
end; $$;

grant execute on function public.class_app_log_operation(text, text, text, jsonb) to authenticated;

-- Note: This audit log provides visibility into operations but does not prevent spoofing.
-- The x-class-username header can still be spoofed, but operations will be logged.
-- Phase 3 will replace the header-based identity model with server-validated JWT claims.
