-- Migration 019: Add operation audit log for sensitive actions
-- Depends on: 017 (class_app_is_admin updated), 018 (admin function grants)
-- Status: PENDING — run after migration 018
--
-- Purpose: Record sensitive operations so admin can detect spoofing attempts.
-- Writes are restricted to sessions with a non-null class_app_username()
-- (i.e. sessions that have set the x-class-username header). Reads are
-- admin-only.

create table if not exists public.operation_audit_log (
  id             bigint generated by default as identity primary key,
  operation_type text not null,
  table_name     text not null,
  record_id      text,
  actor_username text,
  details        jsonb,
  created_at     timestamptz not null default now()
);

create index if not exists idx_audit_log_created_at on public.operation_audit_log(created_at desc);
create index if not exists idx_audit_log_actor      on public.operation_audit_log(actor_username);
create index if not exists idx_audit_log_operation  on public.operation_audit_log(operation_type);

alter table public.operation_audit_log enable row level security;

-- Admins can read the audit log
drop policy if exists "audit read admin" on public.operation_audit_log;
create policy "audit read admin" on public.operation_audit_log
  for select using (public.class_app_is_admin());

-- Only sessions with an identified username may write audit entries.
-- This prevents anonymous noise from flooding the log.
drop policy if exists "audit write any"           on public.operation_audit_log;
drop policy if exists "audit write authenticated" on public.operation_audit_log;
create policy "audit write authenticated" on public.operation_audit_log
  for insert with check (public.class_app_username() is not null);

-- Helper function to log operations
create or replace function public.class_app_log_operation(
  p_operation_type text,
  p_table_name     text,
  p_record_id      text  default null,
  p_details        jsonb default null
)
returns void language plpgsql security definer set search_path = public as $$
begin
  insert into public.operation_audit_log
    (operation_type, table_name, record_id, actor_username, details)
  values
    (p_operation_type, p_table_name, p_record_id, public.class_app_username(), p_details);
end; $$;

do $$ begin
  grant execute on function public.class_app_log_operation(text, text, text, jsonb) to authenticated;
exception when others then null; end $$;
