-- Migration 022: Student usefulness — summary history + quiz history
-- Depends on: 021
-- Status: PENDING — run after migration 021
--
-- Purpose: Give students a persistent record of their AI summaries and
-- quiz results. Both tables are private to the owning student.

-- ── AI SUMMARY HISTORY ───────────────────────────────────────────

create table if not exists public.summary_history (
  id           bigint generated by default as identity primary key,
  username     text not null,
  source_name  text not null default '',
  summary_text text not null default '',
  created_at   timestamptz not null default now()
);

create index if not exists idx_summary_history_username
  on public.summary_history(username, created_at desc);

alter table public.summary_history enable row level security;

-- Users can only read their own summaries
drop policy if exists "summary history read own" on public.summary_history;
create policy "summary history read own"
  on public.summary_history for select
  using (username = public.class_app_username());

-- Users can insert their own summaries (enforced by backend as well)
drop policy if exists "summary history insert own" on public.summary_history;
create policy "summary history insert own"
  on public.summary_history for insert
  with check (username = public.class_app_username());

-- Users can delete their own summaries
drop policy if exists "summary history delete own" on public.summary_history;
create policy "summary history delete own"
  on public.summary_history for delete
  using (username = public.class_app_username());

-- Admins can read all summaries (for moderation)
drop policy if exists "summary history read admin" on public.summary_history;
create policy "summary history read admin"
  on public.summary_history for select
  using (public.class_app_is_admin());

-- ── QUIZ HISTORY ─────────────────────────────────────────────────

create table if not exists public.quiz_history (
  id           bigint generated by default as identity primary key,
  username     text not null,
  source_name  text not null default '',
  score        integer not null default 0,
  total        integer not null default 0,
  taken_at     timestamptz not null default now()
);

create index if not exists idx_quiz_history_username
  on public.quiz_history(username, taken_at desc);

alter table public.quiz_history enable row level security;

drop policy if exists "quiz history read own" on public.quiz_history;
create policy "quiz history read own"
  on public.quiz_history for select
  using (username = public.class_app_username());

drop policy if exists "quiz history insert own" on public.quiz_history;
create policy "quiz history insert own"
  on public.quiz_history for insert
  with check (username = public.class_app_username());

drop policy if exists "quiz history delete own" on public.quiz_history;
create policy "quiz history delete own"
  on public.quiz_history for delete
  using (username = public.class_app_username());

drop policy if exists "quiz history read admin" on public.quiz_history;
create policy "quiz history read admin"
  on public.quiz_history for select
  using (public.class_app_is_admin());
