-- Migration 023: Subjects table
-- Depends on: 015 (admins table + class_app_is_admin), 021 (lockdown pattern)
-- Status: PENDING — run after migration 022
--
-- PURPOSE:
-- Replaces the localStorage-only admin subject storage with a persistent
-- Supabase table. Admins can add subjects to any year/semester from the UI;
-- subjects are visible to all users immediately and survive browser data clears.
--
-- SECURITY MODEL:
--   SELECT — public (subjects are not secret)
--   INSERT / UPDATE / DELETE — server only (service key bypasses RLS)
--   Direct browser clients cannot write to this table (no client write policies).
--   Server routes enforce requireAdmin (JWT isAdmin flag) before touching this table.
--
-- NOTE: grid_key values match SUBJECT_GRID_MAP keys in script.js:
--   'first' | 'second' | 'y2first' | 'y2second' |
--   'y3first' | 'y3second' | 'y4first' | 'y4second'

create table if not exists public.subjects (
  id          bigint generated by default as identity primary key,
  grid_key    text        not null,
  code        text        not null,
  teacher     text        not null default '',
  icon        text        not null default '📚',
  created_by  text        not null default '',
  created_at  timestamptz not null default now(),

  -- Prevent duplicate subject codes within the same semester grid
  constraint subjects_grid_code_unique unique (grid_key, code)
);

-- Enable RLS
alter table public.subjects enable row level security;

-- Anyone (including unauthenticated) can read subjects
drop policy if exists "subjects public read" on public.subjects;
create policy "subjects public read"
  on public.subjects for select using (true);

-- No direct client INSERT — server uses service key (bypasses RLS)
-- No direct client UPDATE
-- No direct client DELETE
-- (Absence of write policies = deny by default under RLS)

-- Index to speed up grid_key lookups (one query per page load)
create index if not exists subjects_grid_key_idx on public.subjects (grid_key);

comment on table public.subjects is
  'Admin-managed subject list for each year/semester grid. '
  'Writes are server-only (service key). Reads are public.';
